name: build
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        poetry-version: ["1.8.2"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: ${{ matrix.poetry-version }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}