name: Docs
on:
  push:
    branches:
      - master


jobs:
  build-docs:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: abatilo/actions-poetry@v2
      - name: install deps
        run: poetry install --only=docs
      - name: build
        run: poetry run mkdocs build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./site"
      - name: Deploy to Pages
        uses: actions/deploy-pages@v2


